'use strict';

const date = document.querySelector('#date');
const input = document.querySelector('input');
const btn = document.querySelector('#addBtn');
const list = document.querySelector('ul');
const deleteBtn = document.querySelector('.delete');
const check = "check";
const unCheck = "unCheck";
const line = "line";
let complete = document.querySelector(".unCheck");
let id;
let tasksArray;
const activeBtn = document.querySelector("#activeBtn");
const completedBtn = document.querySelector("#completedBtn");
const allBtn = document.querySelector("#allBtn");
const show = 'show';
const unShow = 'unShow';
const active = 'active';
const completed = 'completed';
const all = 'all';
const taskNumber = document.querySelector("#tasksLeft");
